version: '3.8'
services:
  lab_storage_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab_storage
    ports:
      - '15432:5432'
    volumes:
      - lab_storage_volume:/var/lib/postgresql/data
volumes:
  lab_storage_volume:
    driver: local
